apiVersion: batch/v1
kind: CronJob
metadata:
  name: kvstore-backup
  namespace: kvstore
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox
            command:
            - sh
            - -c
            - |
              timestamp=$(date +%Y%m%d-%H%M%S)
              tar czf /backup/kvstore-${timestamp}.tar.gz -C /data .
            volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true
            - name: backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: data-kvstore-0
          - name: backup
            persistentVolumeClaim:
              claimName: backup-pvc
